# 关闭防火墙
- name: Remove firewalld
  yum:
    name:
      - firewalld
      - firewalld-filesystem
      - python-firewall
    state: absent



# 配置数据目录
- block:
    - name: Create some directory for pgsql
      file:
        path: "{{ item }}"
        owner: postgres
        group: postgres
        mode: 0700
        state: directory
      with_items:
        - "{{ pgdata }}"
        - "{{ pgArchiveDir }}"

    - name: Create PGDATA directory
      file:
        path: '{{ pgdata }}'
        state: directory
        owner: postgres
        group: postgres
        mode: 0700

    - name: Replace PGDATA for pgsql systemd unit
      replace:
        path: /usr/lib/systemd/system/postgresql-13.service
        regexp: 'Environment=PGDATA=.*'
        replace: 'Environment=PGDATA={{ pgdata }}/'
  tags: pgdata



# 安装
- block:
    - name: Install pgsql repo online
      yum:
        name: "{{ pgsql_repo }}"
        state: present

    - name: install centos-release-scl-rh
      yum:
        name: centos-release-scl-rh
        state: present

    - name: Install pgsql online
      yum:
        name: "{{ pgsql_yum }}"
        state: present
  tags:
    - pgsql_install
    - pgsql_online



- block:
    # 初始化数据库
    - name: Check if file exists in the "{{ pgdata }}"
      stat:
        path: "{{ pgdata }}/postgresql.conf"
      register: pgdata_check

    - name: Initialize pgsql
      shell: /usr/pgsql-13/bin/initdb -D "{{ pgdata }}"
      become: true
      become_user: postgres
      when: not pgdata_check.stat.exists

    #修改postgresql.conf文件
    - name: Copy template postgresql-primary.conf.j2
      template:
        src: postgresql-primary.conf.j2
        dest: "{{ pgdata }}/postgresql.conf"
        owner: postgres
        group: postgres
        mode: 0600

    # 创建数据库用户
    - name: start pgsql
      systemd:
        name: postgresql-13
        state: started
        enabled: true
        daemon_reload: true

    - name: Wait for pgsql
      wait_for:
        host: 0.0.0.0
        port: "{{ pgport }}"
        state: drained
        timeout: 60

    - name: Copy SQL user template
      template:
        src: setUser.sql.j2
        dest: "{{ pghome }}/setUser.sql"
        owner: postgres
        group: postgres
        mode: 0755

    - name: Run SQL user template
      shell: psql -f setUser.sql
      args:
        chdir: "{{ pghome }}"
      become: true
      become_user: postgres

    - name: Delete setUser.sql
      file:
        path: ~/setUser.sql
        state: absent
      become: true
      become_user: postgres

    - name: Copy template pg_hba.conf.j2
      include_tasks: pg_hba.yaml

    # 启动数据库
    - name: restart pgsql
      systemd:
        name: postgresql-13
        state: restarted

  tags: primaryConf
  when: inventory_hostname in groups['pgsqlPrimary']
  #https://blog.csdn.net/qq_37481017/article/details/124933816
  #以下操作只需要在server1机器执行、以postgres用户