---
- name: Remove firewalld
  yum:
    name:
      - firewalld
      - firewalld-filesystem
      - python-firewall
    state: absent

- name: Update system repository
  yum:
    update_cache: yes

- name: Remove unnecessary packages
  yum:
    autoremove: yes

- name: Install sshpass
  yum:
    name: sshpass
    state: present