---
- name: Update system repository
  yum:
    update_cache: yes

- name: Upgrade packages
  yum:
    name: '*'
    state: latest

- name: Remove unnecessary packages
  yum:
    autoremove: yes

- name: Install bash-completion
  yum:
    name: 'bash-com*'
    state: present

- name: Install sshpass
  yum:
    name: sshpass
    state: present

- name: Install psycopg2
  yum:
    name: python3-psycopg2
    state: present
