- hosts: localhost
  connection: local

  tasks:
    - name: Generate SSH key for ansible
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

- hosts: masters
  tasks:
   - name: Distribute authorized key for ansible
    become: true
    become_user: root
    gather_facts: true
    vars_files:
      - "{{ playbook_dir }}/vars/variables.yaml"
    command: sshpass -p {{default_password}} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@{{ ansible_host }}
