- hosts: localhost
  connection: local

  tasks:
    - name: Generate SSH key for ansible
      user:
        name: root
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa


- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  tasks:
    - name: Print the command to be executed
      debug:
        msg: "Executing command: sshpass -p {{ default_password }} ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@{{ ansible_host }}"
#    - name: Distribute authorized key
#      command: sshpass -p <default_password> ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no root@{{ ansible_host }}