- name: Stop Pgpool-II and PostgreSQL services, uninstall packages and clean up directory
  hosts: master,standby
  tasks:
    - name: Stop Pgpool-II service
      systemd:
        name: pgpool-II
        state: stopped
      ignore_errors: true


    - name: Stop PostgreSQL-14 service
      systemd:
        name: postgresql-14
        state: stopped
      ignore_errors: true


    - name: Uninstall PostgreSQL packages
      yum:
        name: 'postgresql*'
        state: absent

    - name: Uninstall Pgpool packages
      yum:
        name: 'pgpool*'
        state: absent

    - name: Autoremove unused packages
      command: yum autoremove -y

    - name: Remove PostgreSQL data directory
      shell: rm -rf /var/lib/pgsql/14/data/

- name: Install and configure Cluster Postgresql14 on nodes
  hosts: master,standby
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:

    - role: update_os

    - role: set_hosts

    - role: postgresql_install

    - role: postgresql_service

    - role: pgpool-II_install

    - role: pgpool-II_config

    - role: passwordless_ssh_config

    - role: log_config

    - role: pgpool_service


- name: disable postgresql-14 service on  postgres1.local
  hosts: postgres1.local
  tasks:
    - systemd:
       name: postgresql-14.service
       enabled: false



- name: disable pgpool-II -2
  hosts: postgres2.local
  tasks:
    - systemd:
        name: pgpool-II
        enabled: false

- name: disable pgpool-II -3
  hosts: postgres3.local
  tasks:
    - systemd:
        name: pgpool-II
        enabled: false


- name: Run initdb_install on  postgres2.local
  hosts: postgres2.local
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:
    - role: postgresql_config




- name: Run initdb_install on  postgres3.local
  hosts: postgres3.local
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:
    - role: postgresql_config


- name: Copy .pgpass and .pcppass files to home directory
  hosts: standby
  tasks:
    - name: Copy .pgpass file to home directory
      command: cp /var/lib/pgsql/14/.pgpass ~/
      become: yes

    - name: Copy .pcppass file to home directory
      command: cp /var/lib/pgsql/14/.pcppass ~/
      become: yes



- name: Restart all remote Linux systems
  hosts: standby
  tasks:
    - name: Reboot the remote system
      reboot:


#
#- name: Start_postgresql-14.service on postgres2.local
#  hosts: postgres2.local
#  tasks:
#   - systemd:
#      name: postgresql-14.service
#      state: started

#
#- name: pg backup on postgres3.local
#  hosts: postgres3.local
#  become: true
#  gather_facts: true
#  vars_files:
#    - "{{ playbook_dir }}/vars/variables.yaml"
#  roles:
#    - role: pg_basebackup_config
#
#

- name: Start_postgresql-14.service on postgres3.local
  hosts: standby
  tasks:
    - systemd:
        name: postgresql-14.service
        state: started


- name: Start_pgpool_servers
  hosts: master
  tasks:
    - systemd:
        name: pgpool-II
        state: started
