- name: Install and configure Cluster Postgresql14 on nodes
  hosts: standby
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:

    - role: update_os

    - role: set_hosts

    - role: postgresql_install

    - role: postgresql_service

    - role: pgpool-II_install

    - role: pgpool-II_config

    - role: passwordless_ssh_config

    - role: log_config

    - role: pgpool_service

- name: Run initdb_install on node2
  hosts: postgres2.local
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:
    - role: postgresql_config


- name: Run initdb_install on node3
  hosts: postgres3.local
  become: true
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:
    - role: postgresql_config


- name: Restart all remote Linux systems
  hosts: all
  tasks:
    - name: Reboot the remote system
      reboot:

- name: Start_postgresql-14.service
  hosts: standby
  tasks:
   - systemd:
      name: postgresql-14.service
      state: started

- name: Start_pgpool_servers
  hosts: standby
  tasks:
   - systemd:
      name: pgpool-II
      state: started