- name: Install and configure Cluster Postgresql14 on nodes
  hosts: masters 
  become: true
  gather_facts: true 
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
  roles:
    
    - role: update_os
    
    - role: set_hosts

    - role: postgresql_install

    - role: postgresql_config

    - role: postgresql_service

    - role: pgpool-II_install

    - role: pgpool-II_config
    
    - role: passwordless_ssh_config

    - role: log_config

    - role: pgpool_service


- name: Restart all remote Linux systems
  hosts: all
  tasks:
    - name: Reboot the remote system
      reboot:
