- name: Deploy PostgreSQL Cluster
  hosts: pgsqlHA
  remote_user: root
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  roles:
    - { 
        role: postgresql
      }
    - { 
        role: pgpool-ii
      }
  tasks:
  - name: Copy template .pgpass
    include_tasks: roles/postgresql/tasks/pgpass.yaml
  - name: start pgpool
    systemd:
      name: pgpool-II
      state: started
      enabled: true