- name: Install and configure Cluster Postgresql14 on nodes
  hosts: masters 
  become: true
  gather_facts: true 
  vars_files:
    - "{{ playbook_dir }}/vars/variables.yaml"
    -
  - name: execute some log related shell commands
    ansible.builtin.script: "{{ playbook_dir }}/scripts/config.sh"

  roles:
    
    - role: update_os
    
    - role: set_hosts


    - role: postgresql_install

    - role: postgresql_config

    - role: postgresql_service

    - role: log_config

    - role: pgpool-II_install

    - role: pgpool-II_config

    - role: pgpool_service


    - role: passwordless_ssh_config



- name: Restart all remote Linux systems
  hosts: all
  tasks:
    - name: Reboot the remote system
      reboot:
