---

- name: Create the postgresql-14 service
  template:
    src: services/postgresql-14.service.j2
    dest: /lib/systemd/system/postgresql-14.service
    owner: root
    group: root
    mode: '0644'

# 重新加载systemd管理器配置，确保系统中的服务配置更改能够立即生效
- name: Reload systemd manager configuration
  systemd:
    daemon_reload: true

- name: Enable postgresql-14 service
  systemd:
    name: postgresql-14.service
    enabled: true