- hosts: localhost
  tasks:
  - name: Generate SSH key for user postgres for the pgpool
    user:
      name: root
      generate_ssh_key: true
      ssh_key_bits: 2048
      ssh_key_file: "~/.ssh/id_rsa"
    tags: sshkey

- hosts: 
    - pgsqlPrimary
    - pgsqlStandby
  roles:
    - { role: postgresql}

