---

- name: create service pgpool-II
  template:
    src: services/pgpool-II.service.j2
    dest: /lib/systemd/system/pgpool-II.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart pgpool-II

- name: Start Pg-Pool II
  systemd:
    name: pgpool-II
    state: started
