---

- name: create service pgpool-II
  template:
    src: services/pgpool-II.service.j2
    dest: /lib/systemd/system/pgpool-II.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd manager configuration
  systemd:
    daemon_reload: true


- name: Enable pgpool-II
  systemd:
    name: pgpool-II
    enabled: true